### ISSUE TITLE
Angular profile

### ISSUE THREAD

**Issue by sapanparikh18** [grails-samples/angular-scaffolding-31x#1]
In the video at https://vimeo.com/172777807 you have not used profile=angular. Is that how it should be?

**Comment by jameskleeh** [comment]
You can use the angular profile and it will do most/all of those steps for you, depending on the version. The video was demonstrating how to do everything necessary to work with the scaffolding in an existing application.

**Comment by sapanparikh18** [comment]
Thanks a lot, you are right using the 3.2.M2 I did not have to do anything to setup boiler plate code
